### PR TITLE
Update SAG.py

### PR DESCRIPTION
**Pull request by bankenichi**
I butchered your beautiful code to make it play nice with any size and shape tensor, and all base models and resolutions I could think to test. I am god awful at coding, but it seems to work fine.

### CODE REVIEW

**Comment by AG-w** [comment]
ooh that's nice

I found that there are already `shared.sd_model.is_sdxl` `shared.sd_model.is_sd2` `shared.sd_model.is_sd1` bool to check what base model is, so I think base model and custom resolution part can be simplified

**Comment by bankenichi** [comment]
I have no doubt a lot of the code spaghetti I made can be simplified, I just dont have the skills to do it. Feel free to use it or change anyway you like tho.

**Comment by AG-w** [comment]
@bankenichi ok, so I keep wondering why image is a little distorted under certain condition
I found that this part
```python
        middle_layer_latent_size = [
            math.ceil(latent_h / (h * block_scale)),
            math.ceil(latent_w / (h * block_scale))
        ]
        if middle_layer_latent_size[0] * middle_layer_latent_size[1] < hw1:
            middle_layer_latent_size = [
                math.ceil(latent_h / ((h/2) * block_scale)),
                math.ceil(latent_w / ((h/2) * block_scale))
            ]
```
It's supposed to be 
```python
        middle_layer_latent_size = [
            math.ceil(latent_h / h) * block_scale,
            math.ceil(latent_w / h) * block_scale
        ]
        if middle_layer_latent_size[0] * middle_layer_latent_size[1] < hw1:
            middle_layer_latent_size = [
                math.ceil(latent_h / (h/2)) * block_scale,
                math.ceil(latent_w / (h/2)) * block_scale
            ]
```
now image no longer distorted and there's no need of `find_closest_factors()` (this function is probably the reason image get distorted)

**Comment by AG-w** [comment]
@bankenichi ok, so I keep wondering why image is a little distorted under certain condition
I found that this part
```python
        middle_layer_latent_size = [
            math.ceil(latent_h / (h * block_scale)),
            math.ceil(latent_w / (h * block_scale))
        ]
        if middle_layer_latent_size[0] * middle_layer_latent_size[1] < hw1:
            middle_layer_latent_size = [
                math.ceil(latent_h / ((h/2) * block_scale)),
                math.ceil(latent_w / ((h/2) * block_scale))
            ]
```
It's supposed to be 
```python
        middle_layer_latent_size = [
            math.ceil(latent_h / h) * block_scale,
            math.ceil(latent_w / h) * block_scale
        ]
        if middle_layer_latent_size[0] * middle_layer_latent_size[1] < hw1:
            middle_layer_latent_size = [
                math.ceil(latent_h / (h/2)) * block_scale,
                math.ceil(latent_w / (h/2)) * block_scale
            ]
```
now image no longer distorted and there's no need of `find_closest_factors()` (this function is probably the reason image get distorted)

**Pull request merged**
